### ISSUE TITLE
Gravestone Mod Soft Lock

### ISSUE THREAD

**Issue by ConnorVex** [PneumonoIsNotAvailable/Gravestones#10]
I died while flying a plane(Immersive aircraft addon: man of many planes)

and now I can't log into the server to get my stuff because every time I try, the client spits this out in the 'Latest Log'
https://mclo.gs/TWoBoQm

**Comment by PneumonoIsNotAvailable** [comment]
The crash is due to not null-checking the grave owner, which was fixed when I updated the mod to 1.21. I only really work on the latest version and older ones aren't supported just because I mostly do this for fun and backporting/maintaining multiple versions is just really annoying. I can make a version of 1.0.4 that fixes this and send it here but I won't be actively maintaining it in the future. Sorry!

**Comment by PneumonoIsNotAvailable** [comment]
[gravestones-1.0.4-1.20.1.zip](https://github.com/user-attachments/files/16154547/gravestones-1.0.4-1.20.1.zip)
This version won't crash since it disables text rendering for the gravestones. It's possible that the gravestone in your server won't recognise you as owner due to how immersive aircraft handles planes, in this case you should switch to creative mode and break the grave by hand, which will still drop all the items. I'd recommend switching to another gravestone mod which actively supports 1.20.1, because other issues like this might pop up.
