### ISSUE TITLE
Trinkets Support: Trinkets are destroyed when unable to return

### ISSUE THREAD

**Issue by vercte** [PneumonoIsNotAvailable/Gravestones#16]
I've been testing around, and I've found that when a grave is collected by a Create mod Deployer on a contraption [an entity with inventory, but no trinket slots] my grave gets collected but my trinkets (backpack, goggles) are destroyed with no trace.

Looking at the code in [TrinketsSupport.java](https://github.com/PneumonoIsNotAvailable/Gravestones/blob/514ae85477f49578c671357f5cfe9dfc221a7933/src/main/java/net/pneumono/gravestones/TrinketsSupport.java#L89), I see that an item is spawned when it can't find a trinket slot. Something could be going on in the check? I can't reproduce this on singleplayer, only on a dedicated server.

**Comment by PneumonoIsNotAvailable** [comment]
Looking at the code for deployers, I think that the way Trinkets adds it's slots means that deployers do have slots (which is why the items don't just go onto the ground) but aren't built to properly support them, meaning when the deployer is broken it doesn't know it also needs to drop Trinkets, and they're just deleted. Normally this isn't an issue, since there aren't many situations where a deployer would be given trinkets, but obviously this is one of them.

Deployers shouldn't be able to access gravestones anyway though, so I've just added some code that stops that, which means this is now "fixed". New version (assuming you're using 1.20.1) is [here](https://modrinth.com/mod/pneumono_gravestones/version/1.0.9-1.20.1).
