### ISSUE TITLE
Entity ticking crash with Gravestone mod

### ISSUE THREAD

**Issue by Cry0syn** [PneumonoIsNotAvailable/Gravestones#20]
Hey me and my friends just started a server and we are using your gravestone mod and we found that when we were killed by a mob the server would crash but when we disabled the mod and died to a mob the server wouldn't crash. We don't know why this is occurring. We are using the 1.21 Fabric version.

Here's the crash report:
[crash-2024-08-09_00.41.22-server.txt](https://github.com/user-attachments/files/16556313/crash-2024-08-09_00.41.22-server.txt)

**Comment by Cry0syn** [comment]
We assume its the mod but we don't actually know. Kind of new to this.

**Comment by PneumonoIsNotAvailable** [comment]
I downloaded all the mods you were using, and couldn't replicate this. I'm not sure how it's even possible to cause that crash, since it would require the gravestone data to be missing data in a very specific way that I put things in place to prevent. Is there anything else unique about your situation?

**Comment by Cry0syn** [comment]
I have no idea. It randomly started to happening and when we disabled the mod the it stopped. I'll check in the config or the file itself to see if something is missing.

**Comment by PneumonoIsNotAvailable** [comment]
Misclick, oops!
...Actually I probably should close this issue
