### ISSUE TITLE
Toggleable explosion proofing 

### ISSUE THREAD

**Issue by Com2486** [PneumonoIsNotAvailable/Gravestones#25]
A few of my server members have lost stuff due to dying in explosions, which blew up the gravestones instantly, dropping all the items in them.

**Comment by PneumonoIsNotAvailable** [comment]
Are you using the latest version of the mod (1.0.9)? This was a bug in older versions but as far as I'm aware it should have been fixed since. This could also be caused if you have other mods installed that change explosions in some way, since gravestones has to edit some vanilla code in order to make the gravestones explosion proof, and a different mod might stop gravestones doing what it needs to.

Please provide some more information on what other mods you're using if it isn't an issue with the mod version.

**Comment by Com2486** [comment]
Latest version of the mod. The death that sparked this was from my own mod's Quartz Blade which shoots a (builtin) FireballEntity. AFAIK none of my mods change how explosions work. here's a list:
![image](https://github.com/user-attachments/assets/040dd2c8-4aa5-4dda-a011-3af0fb26af0a)

Also, IIRC i think there's an "on break" event that calls for explosions too that you can just cancel. Might be wrong though, quite new to modding.

**Comment by PneumonoIsNotAvailable** [comment]
I can't recreate this with these mods, is there anything else that might have caused it? If you're able to consistently recreate this yourself, can you send a video of it in action? Thanks.

As for the "on break" event: I was mis-remembering! The mod does just cancel gravestones being broken by overwriting `onExploded`. Mixins were the method the mod used to use until there was an issue with them and I switched to the current method.

**Comment by Com2486** [comment]
I was able to recreate it in both singleplayer and multiplayer consistently, will send a video
I know it's the explosion breaking a gravestone because turning off mobgriefing reveals the gravestone.
[Here's a short video, uploaded to youtube because github doesn't like file sizes.](https://youtu.be/ztK6vXNm_hE)

**Comment by PneumonoIsNotAvailable** [comment]
Hmm, does it happen with only gravestones installed? If not, can you try and figure out which mod it's incompatible with? Probably should've suggested this earlier, my bad.

Also thanks for the kind words in the video description!

**Comment by Com2486** [comment]
Tried on a clean modpack, still having issues. Here's the whole setup for whatever it's worth.

Linux Mint 22 Cinnamon
Ryzen 5 3600
RTX3060
MultiMC, latest version
1.20.1, Fabric loader 0.16.9

Fabric API 0.92.2+1.20.1
Gravestones 1.0.9-1.20.1
Mod Menu 7.2.2
PneumonoCore 1.1.4+1.20.1

The mod also logs "Placed Com2486's Gravestone at (38, 71, 103)", but all the items are still on the floor.
It doesn't show the "Com2486 has found their grave at (location)" either

**Comment by Com2486** [comment]
UPDATE: Using the runClient task directly cloned from the repo, it seems to work. Maybe it's the Modrinth build, or something?

**Comment by Com2486** [comment]
Alright I think i've come to the solution. [The TechnicalGravestone block](https://github.com/PneumonoIsNotAvailable/Gravestones/blob/1.20.1/src/main/java/net/pneumono/gravestones/content/TechnicalGravestoneBlock.java) doesn't seem to have an on-explode event for 1.20.1. This may be our issue.

**Comment by PneumonoIsNotAvailable** [comment]
I think I've figured it out!
The 1.21 version of the mod overwrites `onExploded` like I said, but that method doesn't exist in 1.20.1. It looks like I deleted the mixin in both versions, but only added a different way of handling explosions to 1.21 (presumably because I forgot after realising 1.20.1 didn't have `onExploded`)
I have absolutely no idea how this hasn't been noticed all this time, especially considering I myself have managed multiple servers using this version of the mod. I also don't know how I was unable to recreate it earlier...

**Comment by PneumonoIsNotAvailable** [comment]
Oh wow that was weird timing

**Comment by Com2486** [comment]
Great timing yeah lol. Well, glad I could help lol. I might make a prq or something. Thanks for being so cooperative

**Comment by PneumonoIsNotAvailable** [comment]
Thank you too! I can probably just re-add the mixin, you shouldn't need to make a prq

**Comment by PneumonoIsNotAvailable** [comment]
New version should be [here](https://modrinth.com/mod/pneumono_gravestones/version/1.0.10-1.20.1). Sorry about this whole situation, it's really bad that this managed to slip under my radar.

**Comment by Com2486** [comment]
No worries! Again, this mod is one of the better gravestones, COMPLETELY fine with waiting 3 days compared to three months for a fix like some of the others
