### ISSUE TITLE
Gravestone and water

### ISSUE THREAD

**Issue by Adambtrambira** [PneumonoIsNotAvailable/Gravestones#4]
A friend's grave broke when he died in the water and lost items because of it

**Comment by PneumonoIsNotAvailable** [comment]
I can't recreate this in singleplayer or on a server. Were you playing with any other mods that might affect deaths?

**Comment by Adambtrambira** [comment]
We play with mods, but not with those that can affect death. He just drowned and that grave broke because of the water. The only thing he could do with it was take it in his hand and put it on others and destroy it again, but he didn't get any loot from that.

**Comment by PneumonoIsNotAvailable** [comment]
No types of graves are breakable from water (unless you're playing with a mod that changes water behaviour), in fact all types (both aesthetic and functional) are waterloggable.

If you mean he could pick up the gravestone itself as an item, only aesthetic gravestones have item forms for breaking/placing, so the only way this could have happened was if the mod somehow placed an aesthetic gravestone instead of a functional one (which should be impossible) or if an aesthetic gravestone was somehow mixed up with a functional one.

I have honestly no idea how this could have happened, sorry.
